version: '3.8'

services:
  auth:
    image: jboss/keycloak:16.1.1
    ports:
      - 8001:8080
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
    volumes:
      - auth-db:/opt/jboss/keycloak/standalone/data/

  client:
    build: 
      context: ./frontend
    ports:
      - 8000:80
    
volumes:
  auth-db: